change design in home page and traditional food
AlaniaShota/Georgia pull request #2
Opened 2023-11-22 16:09 UTC by AlaniaShota

2023-11-22 16:33 UTC, AlaniaShota commented on src/Components/Header.jsx
>                      <Link to='gid' className=' mr-4 py-1 lg:px-4 sm:px-14'>Tour Guide</Link>
DRY

2023-11-22 16:33 UTC, AlaniaShota commented on src/Components/Header.jsx
>                          {open ? <FontAwesomeIcon icon={faXmark} size='lg' /> : <FontAwesomeIcon icon={faBars} size='lg' />}
იფ ქონდეშენი გიწერია არასწორ ადგილას, უნდა შეამოწმო faXmark & faBars

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/Home/Home.jsx
> +                            <p>Georgia is located at the intersection of Europe and Asia, on the shores of the Black Sea, in the Caucasus Mountains. For centuries, it has served to connect civilizati
ტექსტები გაიტანე კონსტანტ ფაილში. დაარქვი შესაბამისი სახელები და დააიმპორტე

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/Home/Home.jsx
> +                {/* <div className=" "> */}
კომენტარები არ დატოვო თუ რამეს არ ხსნი

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/Home/Home.jsx
> +                {/* </div> */}
კომენტარი

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/TraditionalFood/Components/Card/FoodCard.jsx
> +                    on this opportunity to immerse yourself in the culture of the country through its gastronomy!
კონსტანტ ფაილში

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/TraditionalFood/Components/TraditionalFoodLibery.jsx
> +                    <RandomFood key={index} randomFood={item} designClass={index === 0 ? 'flex-row rounded-r-lg' : ' flex-row-reverse rounded-l-lg'} />
სცადე რო ჯს-ს ნაცვლად css სელექტორით გააკეთო იგივე

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/TraditionalFood/TraditionalFood.jsx
> +          <p className='w-[497px] text-[#fff] text-base font-normal'>Georgia is known for its rich culinary tradition, influenced by the best techniques and traditions of Europe and the East. Its cui
კონსტანტ ფაილში

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/TraditionalFood/TraditionalFood.jsx
> +        </div>
კონსტანტ ფაილში

2023-11-22 16:33 UTC, AlaniaShota commented on src/Pages/TraditionalFood/TraditionalFood.jsx
> +                  way is crucial. That`s why usually the most eloquent and respected attendee of the meal is appointed as the tamada.
კონსტანტ ფაილში

2023-11-24 13:30 UTC, DiannaShonia requested changes

2023-11-24 13:30 UTC, DiannaShonia commented on src/Pages/Home/constants.js
> +export const geographyDescription =
კონსტანტებს დიდი ასოთი და ტირეებით რო დაარქვა სახელი უკეთესი პრაქტიკაა

2023-11-24 13:30 UTC, DiannaShonia commented on src/Pages/TraditionalFood/Components/TraditionalFoodLibery.jsx
> +const leadMoreContent = 15;
ეს უფრო ფუნქციის სახელია ვიდრე ცვლადის, loadMoreContentCount ან loadMoreContentLimit რაღაცა მსგავსი დაარქვი

2023-11-24 13:30 UTC, DiannaShonia commented on src/Pages/TraditionalFood/Components/TraditionalFoodLibery.jsx
> +                  Most iconic:{" "}
ბრეკეტები ზედმეტია

2023-11-24 13:30 UTC, DiannaShonia commented on src/Pages/TraditionalFood/TraditionalFood.jsx
> +          <h1 className="text-left text-2xl text-[#fff] font-bold cursor-default">
text-[#fff] :) :) :)

2023-11-24 13:30 UTC, DiannaShonia commented on src/Pages/TraditionalFood/TraditionalFood.jsx
> +          <p className="w-[497px] text-[#fff] text-base font-normal cursor-default">
გაიტანე კონფიგში ფერი!!

2023-11-24 13:30 UTC, DiannaShonia commented on src/Pages/TraditionalFood/TraditionalFood.jsx
> +              <p className="w-[497px] text-[#fff] text-base font-normal cursor-default">
text-base default ად აქვს ისედაც და ცალკე გაწერა არ გინდა, რესპონსივის დროს თუ ცვლი ფონტს ან რამეს გამო თუ ცვლი მოკლედ მხოლოდ მაშინ

2023-11-24 13:30 UTC, DiannaShonia commented on src/Router/Router.jsx
src/routes/routes.tsx  უნდა იყოს სახელი ფოლდერის და ფაილის. როუტების სია გაქვს ცალკე გატანილი და არა როუტერი

2023-11-24 13:30 UTC, DiannaShonia commented on tailwind.config.js
> +        whiteText: "#ffffff",
ფერებს სახელები ელემენტების მიხედვით არ დაარქვა

თუ მაგალითად გაქვს ლურჯი ფერი და მერე უფრო ღია ლურჯი ან ცისფერი, შეგიძლია ესე დაწერო blue-500 და blue-300. 500 ნიშნავს მუქს და 300 უფრო ღიას ვიდრე 500 იანი 

ან შეგიძლია გამოიყენო button-primary, button-secondary როცა ბათონზე ორი ფერი გაქვს, მაგრამ 99% ბათონის ფერები ბრენდის ფერებია და ბათონის გარდა ბევრგან გამოიყენებ ამიტომ ბათონი რო დაარქვა არ იქნება ლოგიკური

2023-11-29 16:16 UTC, DiannaShonia approved these changes

2023-11-29 16:17 UTC, merged